/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiPublicGenerateDeckRouteImport } from './routes/api/public/generate-deck'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicX402StatusRouteImport } from './routes/api/public/x402-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateDeckRoute = ApiPublicGenerateDeckRouteImport.update({
  id: '/api/public/generate-deck',
  path: '/api/public/generate-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicX402StatusRoute = ApiPublicX402StatusRouteImport.update({
  id: '/api/public/x402-status',
  path: '/api/public/x402-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/public/generate-deck': typeof ApiPublicGenerateDeckRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/x402-status': typeof ApiPublicX402StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/public/generate-deck': typeof ApiPublicGenerateDeckRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/x402-status': typeof ApiPublicX402StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/public/generate-deck': typeof ApiPublicGenerateDeckRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/x402-status': typeof ApiPublicX402StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/api/public/generate-deck'
    | '/api/public/health'
    | '/api/public/x402-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace'
    | '/api/public/generate-deck'
    | '/api/public/health'
    | '/api/public/x402-status'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/api/public/generate-deck'
    | '/api/public/health'
    | '/api/public/x402-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiPublicGenerateDeckRoute: typeof ApiPublicGenerateDeckRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicX402StatusRoute: typeof ApiPublicX402StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-deck': {
      id: '/api/public/generate-deck'
      path: '/api/public/generate-deck'
      fullPath: '/api/public/generate-deck'
      preLoaderRoute: typeof ApiPublicGenerateDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x402-status': {
      id: '/api/public/x402-status'
      path: '/api/public/x402-status'
      fullPath: '/api/public/x402-status'
      preLoaderRoute: typeof ApiPublicX402StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiPublicGenerateDeckRoute: ApiPublicGenerateDeckRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicX402StatusRoute: ApiPublicX402StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
